version: '2'
services:
  postgres:
    image: "postgres:9.4"
    environment:
     - POSTGRES_USER=${PGUSER}
     - POSTGRES_PASSWORD=${PGPASSWORD}
     - POSTGRES_DB=techtalks_dev
    expose:
      - 5432
    ports:
     - "5432:5432"
  web:
    build: .
    ports:
     - "3000:3000"
     - "3001:3001"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
    command: /usr/src/app/scripts/docker_start.sh
    environment:
     - RAZZLE_CONNECTION_STRING_DEV=postgres://${PGUSER}:${PGPASSWORD}@postgres/techtalks_dev
